name: Build PR preview

on:
  pull_request:
    # To manage 'surge-preview' action teardown, add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/build-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-20.04
    env:
      COMPONENT_NAME: bonita
      # Except if you want to test in progress work that your content depends on, keep it set to master
      # Also update the path to the action from the bonita-documentation-site repository
      # TODO use master when available
      DOC_SITE_BRANCH: chore/remove_duplications_in_surge_preview_workflow
    steps:
      - name: Compute environment variables
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Build and publish PR preview
        # TODO use master when available
        uses: bonitasoft/bonita-documentation-site/.github/actions/build-and-publish-pr-preview/@chore/remove_duplications_in_surge_preview_workflow
        with:
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          doc-site-branch: ${{ env.DOC_SITE_BRANCH }}
          # '>' Replace newlines with spaces (folded)
          # '-' No newline at end (strip)
          build-preview-command: |
            ./build-preview.bash --branch "${{ env.BRANCH_NAME }}" --component "${{ env.COMPONENT_NAME }}"
